#!/usr/bin/env bash
# I am going to install a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend onemwaniasam
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 6341-web-01 54.89.172.80:80 check
    server 6341-web-02 54.82.194.92:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
