#!/usr/bin/env bash
#SErvers are the pieces of software generating and serving HTML pages
#Installing nginx in web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
service nginx restart
