#!/usr/bin/env bash
#SErvers are the pieces of software generating and serving HTML pages
#Installing nginx in web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'

sed -i '/server_name _;/a \ \ rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

nginx -t && service nginx restart
~                      
